"""Initial migration

Revision ID: 2de281032940
Revises: 99ce1dd07104
Create Date: 2023-05-25 10:43:42.469158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de281032940'
down_revision = '99ce1dd07104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
